if __name__ == "__main__":
    print("=== Tablas de Verdad ===")
    print("\nOR")
    print("0 | 0 = ",False or False)
    print("0 | 1 = ",False or True)
    print("1 | 0 = ",True or False)
    print("1 | 1 = ",True or True)
    print("\nAND")
    print("0 | 0 = ",False and False)
    print("0 | 1 = ",False and True)
    print("1 | 0 = ",True and False)
    print("1 | 1 = ",True and True)
    print("\nNOT")
    print("0 = ",not False)
    print("1 = ",not True)
    print("\n***Comparaciones***")
    print("\n¿1 es igual a 2? (1==2) : ",1==2)
    print("¿1 no es igual a 2? (1!=2) : ",1!=2)
    print("¿1 es mayor a 2? (1>2) : ",1>2)
    print("¿1 es mayor o igual a 2? (1>=2) : ",1>=2)
    print("¿1 es menor a 2? (1<2) : ",1<2)
    print("¿1 es menor o igual a 2? (1<=2) : ",1<=2)